import os
API_ID = int(os.environ.get("API_ID", "20658336"))
API_HASH = os.environ.get("API_HASH", "cedfb5fb4ffee7ecc746b28afc7925e3") 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
OPENAI_KEY = os.environ.get("OPENAI_KEY", "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")
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,None) 
SUDO=os.environ.get("SUDO","5910057231")
BOT_NAME = os.environ.get("BOT_NAME", "ᴛʜᴇɴᴀ ᴀɪ")
START_IMG = os.environ.get("START_IMG","https://telegra.ph/file/4746e2442a584f37dcc86.jpg")
STKR = os.environ.get("STKR","CAACAgEAAx0CRjAUHgABAsULZASkFZUsTQTw2k-FvC2SBJnd-vAAAokCAALW9iBFzemsQBDIqWkuBA")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("UPDATE_CHNL", "BotStuduos")
OWNER_USERNAME = os.environ.get("OWNER_USERNAME", "CerennyFlexQ")
SUDO=os.environ.get("SUDO","5910057231")
SUPPORT_GRP = os.environ.get("SUPPORT_GRP","BotStuduos")
BARD_TOKEN=os.environ.get("BARD_TOKEN","")
